name: stripe_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc_hooks: ^0.0.2+1
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^10.1.1
  # razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - stripe.env
